name: "Run Benchmarks"
description: "Runs code in subfolders, records execution times, and updates README"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.13"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Run benchmark script
      run: python .github/actions/run-benchmarks/run_benchmarks.py
      shell: bash
