name: Functional tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  functional:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up README
        shell: bash
        run: cp tests/README_TEMPLATE.md tests/README.md
      - name: Run our action
        uses: ./
        env:
          GPG_PASS: ${{ secrets.GPG_PASS }}
        with:
          python-version: "3.13"
          working-directory: tests/
      - name: Compare results
        shell: bash
        run: |
          echo "..."
          cat tests/README.md
          echo "..."
          cat tests/EXPECTED_README.md
          echo "..."
          sed -i -E 's/[0-9]+\.[0-9]+/x/' tests/README.md
          sed -i -E 's/[0-9]+/y/' tests/README.md
          sed -i -E 's/[0-9]+/z/' tests/README.md
          diff --ignore-all-space --ignore-blank-lines tests/README.md tests/EXPECTED_README.md
  functional_two:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up README
        shell: bash
        run: cp tests/README_TEMPLATE.md tests/README.md
      - name: Run our action
        uses: ./
        env:
          GPG_PASS: ${{ secrets.GPG_PASS }}
        with:
          python-version: "3.13"
          working-directory: tests/
          dotnet-version: "-1"
          rust-version: "-1"
          ocaml-version: "-1"
          racket-version: "-1"

