name: Functional tests
on: [push, pull_request]
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run Benchmarks
        uses: ./
        with:
          python-version: "3.13"
          working-directory: tests/
      - name: Compare results
        shell: bash
        run: diff README.md EXPECTED_README.md
