name: Lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      # Install our only dependency.
      - run: pip install pyre-check
      - uses: pre-commit/action@v3.0.1
      - run: cd .github/actions/run-benchmarks/ && python test_run_benchmarks.py
        shell: bash
