name: Lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
      - name: Check poetry.lock consistency
        shell: bash
        run: poetry check --lock
      - name: Install dependencies
        shell: bash
        run: poetry install --all-extras
      - uses: pre-commit/action@v3.0.1
