name: Unit Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install .[coverage]
        shell: bash
      - run: |
          coverage run --source advent_of_action -m unittest discover
          COVERAGE=$(coverage report --format total)
          echo "${COVERAGE}"
          [ "$COVERAGE" = 100 ] || exit 1
          python -m pybadges --left-text Coverage --right-text "${COVERAGE}"% > badge.svg
        shell: bash
        working-directory: tests
      - name: Commit results
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git add tests/badge.svg
          git commit -m "Update coverage badge" || echo "No changes to commit"
          git push origin ${{ github.head_ref || github.ref_name }}
