name: Unit Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install .[coverage]
        shell: bash
      - run: |
          coverage run --source advent_of_action -m unittest discover
          COVERAGE=$(coverage report --format total)
          python -m pybadges --left-text Coverage --right-text "${COVERAGE}"% > badge.svg
        shell: bash
        working-directory: tests
